on:
  push:
    branches:
      - develop

name: release-please

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.PAT }}

      - uses: actions/checkout@v4
        if: ${{ steps.release.outputs.prs_created }}
        with:
          ref: ${{ fromJSON(steps.release.outputs.pr).headBranchName }}

      - run: echo "version=`jq -r '.version' package.json | cut -d '.' -f 1,2`" >> $GITHUB_OUTPUT
        id: version

      - run: echo "$(jq '.build.qa.channel="qa-v${{ steps.version.outputs.version }}.0" | .build.production.channel="production-v${{ steps.version.outputs.version }}.0"' eas.json)" > eas.json
        if: ${{ steps.release.outputs.prs_created }}

      - uses: stefanzweifel/git-auto-commit-action@v5
        if: ${{ steps.release.outputs.prs_created }}

      - run: echo "kick off eas build for qa"
        if: ${{ steps.release.outputs.prs_created }}

      - run: echo "kick off uat build once release is on develop branch ${{ steps.release.outputs.releases_created }}"
        if: ${{ steps.release.outputs.release_created }}
