on:
  push:
    branches:
      - develop

name: release-please

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.PAT }}

      - uses: actions/checkout@v4
        with:
          ref: ${{ fromJSON(steps.release.outputs.pr).headBranchName }}

      - run: echo "${{steps.release.outputs}}"

      - run: echo "`jq '.build.qa.channel="qa-v${{ steps.release.outputs.major }}.0.0"' eas.json`"

      - run: echo "kick off eas builds for qa ${{ steps.release.major }}"
        if: ${{ steps.release.outputs.prs_created }}

      - run: echo "kick off uat build once release is on develop branch"
        if: ${{ steps.release.outputs.release_created }}
