on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
  pull_request_target:
    types:
      - opened
      - reopened
      - synchronize
  push:
    branches:
      - develop
      - rptest-v*
  workflow_call:
  workflow_dispatch:

jobs:
  testiness:
    runs-on: ubuntu-latest
    steps:
      - name: Testing!
        run: echo "event ${{ github.event_name }}, ref ${{ github.ref || 'none' }}, head_ref ${{ github.head_ref || 'none' }}, base_ref ${{ github.base_ref || 'none' }}"

  caller:
    name: call
    uses: ./.github/workflows/testy2.yml
    secrets: inherit
