on:
  workflow_call:

jobs:
  testiness2:
    runs-on: ubuntu-latest
    steps:
      - name: Testing!
        run: echo "event ${{ github.event_name }}, ref ${{ github.ref || 'none' }}, head_ref ${{ github.head_ref || 'none' }}, base_ref ${{ github.base_ref || 'none' }}"
